# Generated by Django 2.2.1 on 2019-06-02 02:11

from django.db import migrations, models
import django.utils.timezone
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('poster', models.CharField(max_length=32)),
                ('postid', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('poster', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('content', models.TextField(blank=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField(default=0)),
                ('tags', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=32)),
                ('postid', models.IntegerField()),
                ('rate', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('text', models.TextField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', encrypted_model_fields.fields.EncryptedCharField()),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
