# Generated by Django 2.2.1 on 2019-06-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
