# Generated by Django 2.2.1 on 2019-06-02 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='postid',
            new_name='contentid',
        ),
    ]
